### ISSUE TITLE
4022.29 library version differences from unofficial TwinCAT changelog

### ISSUE THREAD

**Issue by Roald87** [RumstiBumsti/TcLibraryVersions#9]
Hi.

Great initiative! I also started tracking libraries in the [unofficial TwinCAT changelog](https://github.com/Roald87/TwinCatChangelog/blob/main/library_versions.md). Since you have a much more complete picture and scripts to automatically extract the library version (it seems?) I will just link to your repo from mine. 

I did notice a few differences for version 4022.29. For example I have Tc2_IOFunctions at 3.3.12.0 where you have it at 3.3.10.0 and Tc2_Math I have it at 3.3.1.0 and you at 3.3.0.0. Did you extract the versions from a clean install? Then it might be that mine are wrong.

Roald.

**Comment by RumstiBumsti** [comment]
Hi Roald,

thank you. Yes it was a clean install but i will check it again as soon as i have some time. Maybe something went wrong during testing my application.
Yes it automatically extracts the versions but i think i have to add some description how to use it. But since it seems that there is some interest in this application my motivation to do that is increasing :D

BR,
Stefan

**Comment by Roald87** [comment]
Ok then I'll wait until you verified it and then change the link to the library versions on my page such that it points to your repo.

**Comment by RumstiBumsti** [comment]
great thanks!

**Comment by RumstiBumsti** [comment]
Hi Roald,

i verified the versions now and it seems that my list is correct.

Best regards
Stefan

**Comment by Roald87** [comment]
Cool thanks for checking! I've [changed the link](https://github.com/Roald87/TwinCatChangelog/commit/a5c57be8495507ac97ea9d85c9176fb4da2f35c5) so it points to your repo.
